-- Create keys table for rotating header principles
CREATE TABLE IF NOT EXISTS keys (
  id SERIAL PRIMARY KEY,
  header_title TEXT NOT NULL,
  tooltip_marketing TEXT NOT NULL,
  full_lesson JSONB NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE keys ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Allow public read access
CREATE POLICY "Public can view keys" ON keys FOR SELECT USING (true);

-- Insert 20 keys
INSERT INTO keys (header_title, tooltip_marketing, full_lesson) VALUES
('Community is the strongest safety net', 'When economic systems collapse, community remains. The early Christians survived persecution not through individual wealth, but through mutual support and shared resources. Civitas Dei recreates this biblical model for the AI era.', '{"title": "The Power of Community in Economic Crisis", "intro": "History has repeatedly demonstrated: when economies collapse, those who survive and thrive are those who have a solid community around them. Not money, but people are the true safety net.", "verses": ["All the believers were together and had everything in common. They sold property and possessions to give to anyone who had need. - Acts 2:44-45", "Carry each other''s burdens, and in this way you will fulfill the law of Christ. - Galatians 6:2"], "examples": "During the Great Depression, Christian communities that practiced mutual aid passed through the crisis with minimal losses, while individualists suffered enormously. Civitas Dei recreates this model: when a member loses their job, the community becomes their source of income through the services they can offer.", "actions": ["Identify 3 services you can offer to your community", "Join a church that practices Acts 2:44-45", "Build economic relationships based on trust, not contracts", "Invest in community before you need it"]}'),

('Strategic generosity brings prosperity', 'In the Kingdom Economy, those who give sincerely receive more than those who hoard greedily. This principle built the most prosperous societies in history and still works today in Civitas Dei.', '{"title": "The Biblical Principle of Prosperity Through Generosity", "intro": "Western societies did not prosper through savage capitalism, but through Judeo-Christian principles of generosity, trust, and mutual responsibility. When you give sincerely, you receive multiplied.", "verses": ["A generous person will prosper; whoever refreshes others will be refreshed. - Proverbs 11:25", "Whoever sows sparingly will also reap sparingly, and whoever sows generously will also reap generously. - 2 Corinthians 9:6"], "examples": "Providers in Civitas Dei who offer fair prices and excellent services receive more contracts than those who try to exploit. Members who help others without expecting immediate payment build a reputation that becomes more valuable than money.", "actions": ["Offer your first service free to a new member", "Price your services fairly, not maximally", "Leave sincere and constructive reviews", "Recommend other providers when you can''t take a contract"]}'),

('Trust is the foundation of any healthy economy', 'Western societies prospered not through greed, but through trust based on Judeo-Christian principles: the value of one''s word, contract as sacred covenant, and mutual responsibility. Civitas Dei recreates this foundation.', '{"title": "The Economy Based on Biblical Trust", "intro": "The most prosperous economies in history were not built on ruthless competition, but on trust institutionalized through biblical principles. A person''s word was more valuable than a written contract.", "verses": ["A good name is more desirable than great riches; to be esteemed is better than silver or gold. - Proverbs 22:1", "All you need to say is simply ''Yes'' or ''No''; anything beyond this comes from the evil one. - Matthew 5:37"], "examples": "The Western banking system developed in cities with strong Christian tradition - trust was the foundation, not complex contracts. In Civitas Dei, pastoral recommendation + community covenant creates a level of trust impossible to achieve in the secular marketplace.", "actions": ["Keep your word even when it costs you", "Communicate transparently when you can''t deliver what you promised", "Build reputation through consistency, not big promises", "Treat every contract as a sacred covenant"]}'),

('Work is worship when done for the Kingdom', 'Every service offered in Civitas Dei is an act of worship. When you fix a roof, teach a child, or code a website for a brother in Christ, you''re building the Kingdom, not just earning money.', '{"title": "The Theology of Work in the Kingdom Economy", "intro": "The secular world separates work from worship. The Bible never does. Every honest labor done for the glory of God and the good of His people is sacred work.", "verses": ["Whatever you do, work at it with all your heart, as working for the Lord, not for human masters. - Colossians 3:23", "So whether you eat or drink or whatever you do, do it all for the glory of God. - 1 Corinthians 10:31"], "examples": "In medieval Christian guilds, craftsmen saw their work as a calling from God. A carpenter didn''t just build furniture; he participated in God''s creative work. Civitas Dei restores this sacred view of labor.", "actions": ["Pray before starting each job or service", "See every client as a brother or sister in Christ", "Deliver excellence as an offering to God", "Refuse to compromise quality for profit"]}'),

('Debt is spiritual bondage, not financial wisdom', 'The world calls debt ''leverage.'' The Bible calls it slavery. Civitas Dei helps you build wealth through community support and honest labor, not through borrowing from Pharaoh.', '{"title": "Breaking Free from the Debt System", "intro": "Consumer debt is the primary tool of economic enslavement in the modern world. The borrower is slave to the lender - not metaphorically, but literally. Civitas Dei offers an alternative path.", "verses": ["The rich rule over the poor, and the borrower is slave to the lender. - Proverbs 22:7", "Let no debt remain outstanding, except the continuing debt to love one another. - Romans 13:8"], "examples": "When a Civitas Dei member faces unexpected expenses, the community pools resources or offers interest-free loans. When someone loses income, the community provides work. This breaks the cycle of predatory lending.", "actions": ["Calculate your total debt and create a repayment plan", "Commit to zero new consumer debt", "Offer your skills to earn extra income within the community", "Help another member avoid taking on debt"]}'),

('Your reputation is your currency', 'In the secular marketplace, money talks. In Civitas Dei, character talks louder. A good name opens more doors than a fat wallet ever could.', '{"title": "Building Kingdom Reputation", "intro": "Reputation in Civitas Dei isn''t about marketing or personal branding. It''s about consistent character demonstrated over time within a community that knows you deeply.", "verses": ["A good name is more desirable than great riches; to be esteemed is better than silver or gold. - Proverbs 22:1", "The integrity of the upright guides them, but the unfaithful are destroyed by their duplicity. - Proverbs 11:3"], "examples": "In Civitas Dei, members with strong reputations receive opportunities without bidding. Their word is trusted. Their prices are accepted. Their recommendations carry weight. This is Kingdom currency.", "actions": ["Deliver more than you promise, consistently", "Admit mistakes quickly and make them right", "Speak well of other providers, even competitors", "Build relationships before you need transactions"]}'),

('Stewardship, not ownership, is the biblical model', 'You don''t own your skills, your time, or your resources. God does. You''re a steward. Civitas Dei helps you steward well for Kingdom impact.', '{"title": "The Stewardship Economy", "intro": "The modern economy is built on ownership: my money, my property, my business. The Kingdom economy is built on stewardship: God''s resources, temporarily entrusted to me for His purposes.", "verses": ["The earth is the Lord''s, and everything in it, the world, and all who live in it. - Psalm 24:1", "Each of you should use whatever gift you have received to serve others, as faithful stewards of God''s grace. - 1 Peter 4:10"], "examples": "A Civitas Dei member with carpentry skills doesn''t say ''I own this skill.'' He says ''God gave me this skill to serve His people.'' This mindset transforms how we price, serve, and give.", "actions": ["List your skills and ask: How can these serve the Kingdom?", "Tithe your time, not just your money", "Offer pro bono work to those in genuine need", "Invest in training others in your skills"]}'),

('The early church was economically resilient by design', 'Acts 2 wasn''t charity. It was an economic system designed for resilience in persecution. Civitas Dei recreates this design for the AI era.', '{"title": "Acts 2 as Economic Blueprint", "intro": "The early church''s economic model wasn''t idealistic socialism. It was strategic resilience engineering. When Rome persecuted Christians, they couldn''t starve them out because the community was economically self-sufficient.", "verses": ["All the believers were together and had everything in common. They sold property and possessions to give to anyone who had need. - Acts 2:44-45", "There were no needy persons among them. For from time to time those who owned land or houses sold them, brought the money and put it at the apostles'' feet. - Acts 4:34-35"], "examples": "When Roman authorities banned Christians from public markets, they didn''t starve. They had their own internal economy. Civitas Dei recreates this: when AI displaces your job, you have an entire economy waiting for you.", "actions": ["Study Acts 2-4 as an economic manual, not just theology", "Identify which needs in your church could be met internally", "Map your church''s skills and services", "Propose a Civitas Dei pilot to your pastor"]}'),

('Mutual aid is not charity—it''s covenant', 'Charity creates dependence. Mutual aid creates resilience. In Civitas Dei, you give because you''re family, and family takes care of each other.', '{"title": "From Charity to Covenant Economics", "intro": "The secular world has charity: the rich giving to the poor out of pity. The Kingdom has mutual aid: brothers and sisters supporting each other out of covenant love.", "verses": ["Share with the Lord''s people who are in need. Practice hospitality. - Romans 12:13", "If anyone has material possessions and sees a brother or sister in need but has no pity on them, how can the love of God be in that person? - 1 John 3:17"], "examples": "In Civitas Dei, when you help a member, you''re not doing charity. You''re fulfilling covenant. And when you need help, you''re not receiving charity. You''re receiving what the covenant promises.", "actions": ["Reframe ''helping others'' as ''fulfilling covenant''", "Receive help without shame—it''s your covenant right", "Give help without pride—it''s your covenant duty", "Build relationships before crises hit"]}'),

('Skills are more valuable than credentials', 'The world values degrees. The Kingdom values demonstrated ability. In Civitas Dei, what you can do matters more than what paper you hold.', '{"title": "The Skills-Based Kingdom Economy", "intro": "The secular economy is credentialist: you need degrees, certifications, licenses. The Kingdom economy is skills-based: can you actually do the work? Civitas Dei rewards competence, not credentials.", "verses": ["Do you see someone skilled in their work? They will serve before kings. - Proverbs 22:29", "Whatever you do, work at it with all your heart, as working for the Lord. - Colossians 3:23"], "examples": "A self-taught programmer in Civitas Dei gets hired based on portfolio, not degree. A carpenter is judged by his furniture, not his certificate. This opens opportunity to those locked out of credentialist systems.", "actions": ["Build a portfolio of your actual work", "Offer to demonstrate your skills before asking for payment", "Mentor someone in your skill, regardless of their credentials", "Hire based on demonstrated ability, not résumé"]}'),

('Time is the ultimate non-renewable resource', 'You can make more money. You can''t make more time. Civitas Dei helps you invest your time in eternal Kingdom work, not just temporal profit.', '{"title": "Redeeming Time in the Kingdom Economy", "intro": "The secular economy treats time as money. The Kingdom economy treats time as life itself—the raw material of eternity. How you spend your time determines what you build forever.", "verses": ["Be very careful, then, how you live—not as unwise but as wise, making the most of every opportunity. - Ephesians 5:15-16", "Teach us to number our days, that we may gain a heart of wisdom. - Psalm 90:12"], "examples": "A Civitas Dei member chooses to work 30 hours/week at lower pay to have time for discipleship, family, and community service. This isn''t poverty—it''s Kingdom wealth.", "actions": ["Calculate how many hours you have left in life", "Audit where your time actually goes each week", "Identify one hour per week to give to Kingdom work", "Choose relationships over revenue when they conflict"]}'),

('Contentment is the secret to financial freedom', 'The world says you need more. The Bible says you have enough. Civitas Dei helps you discover that contentment, not consumption, brings true wealth.', '{"title": "The Radical Economics of Contentment", "intro": "Consumer capitalism requires perpetual dissatisfaction. You must always want more. Kingdom economics teaches contentment: having enough is having everything.", "verses": ["Godliness with contentment is great gain. For we brought nothing into the world, and we can take nothing out of it. - 1 Timothy 6:6-7", "Keep your lives free from the love of money and be content with what you have. - Hebrews 13:5"], "examples": "Civitas Dei members who practice contentment need less income, work less, stress less, and have more time for Kingdom work. Contentment isn''t poverty—it''s liberation from the hedonic treadmill.", "actions": ["List 10 things you have that you once desperately wanted", "Practice a 30-day buying freeze", "Give away something valuable you no longer need", "Calculate your ''enough number''—what income actually satisfies your needs"]}'),

('The Sabbath principle protects you from burnout', 'God rested on the seventh day not because He was tired, but to model rhythm for us. Civitas Dei builds Sabbath into its economic design.', '{"title": "Sabbath Economics: Rest as Resistance", "intro": "The secular economy demands 24/7 hustle. The Kingdom economy mandates rest. Sabbath isn''t laziness—it''s trust that God provides even when you''re not working.", "verses": ["Remember the Sabbath day by keeping it holy. Six days you shall labor, but the seventh day is a sabbath to the Lord. - Exodus 20:8-9", "Come to me, all you who are weary and burdened, and I will give you rest. - Matthew 11:28"], "examples": "Civitas Dei providers who honor Sabbath report less burnout, higher quality work, and more sustainable businesses. Rest isn''t lost productivity—it''s strategic renewal.", "actions": ["Choose one day per week for complete rest from paid work", "Turn off work notifications on your Sabbath", "Spend Sabbath in worship, family, and community", "Trust God to provide even when you''re not hustling"]}'),

('Transparency builds trust faster than marketing', 'The world hides weaknesses and markets strengths. The Kingdom confesses weaknesses and lets God show strength. Civitas Dei rewards honesty over hype.', '{"title": "Radical Transparency in Kingdom Business", "intro": "Marketing is about controlling perception. Kingdom economics is about revealing reality. When you''re transparent about limitations, failures, and pricing, trust grows exponentially.", "verses": ["Therefore each of you must put off falsehood and speak truthfully to your neighbor, for we are all members of one body. - Ephesians 4:25", "The Lord detests lying lips, but he delights in people who are trustworthy. - Proverbs 12:22"], "examples": "A Civitas Dei provider says ''I''ve never done this exact job before, but I''m willing to learn and charge less.'' This honesty builds more trust than false expertise.", "actions": ["Disclose your limitations upfront", "Explain your pricing clearly, including your profit margin", "Admit mistakes immediately and publicly", "Ask for feedback and actually implement it"]}'),

('Delayed gratification is the path to generational wealth', 'Consumer culture demands instant gratification. Kingdom culture practices patient accumulation. Civitas Dei helps you build wealth that lasts generations.', '{"title": "The Long Game: Building Generational Kingdom Wealth", "intro": "The secular economy is optimized for quarterly profits. The Kingdom economy is optimized for generational impact. What you build today should serve your great-grandchildren.", "verses": ["A good person leaves an inheritance for their children''s children. - Proverbs 13:22", "The plans of the diligent lead to profit as surely as haste leads to poverty. - Proverbs 21:5"], "examples": "Civitas Dei members who save 20% of income, avoid debt, and invest in skills create wealth that compounds over decades. Their children inherit not just money, but a Kingdom economic system.", "actions": ["Save 20% of every payment before spending anything", "Invest in skills that will be valuable in 20 years", "Teach your children Kingdom economics from age 5", "Build assets that produce income without your labor"]}'),

('Excellence is evangelism in the marketplace', 'When you deliver exceptional work as a Christian, you preach without words. Civitas Dei members are known for quality that reflects the character of God.', '{"title": "Excellence as Worship and Witness", "intro": "Mediocre work with a Christian label is worse than excellent work with no label. When you deliver excellence, you demonstrate the character of the God you serve.", "verses": ["Whatever you do, work at it with all your heart, as working for the Lord, not for human masters. - Colossians 3:23", "Let your light shine before others, that they may see your good deeds and glorify your Father in heaven. - Matthew 5:16"], "examples": "A Civitas Dei plumber who shows up on time, cleans up perfectly, and charges fairly becomes a walking sermon. His work preaches the gospel of a God who does all things well.", "actions": ["Deliver 10% more than you promised", "Clean up better than you found it", "Follow up after the job to ensure satisfaction", "Never use ''I''m a Christian'' as an excuse for mediocrity"]}'),

('Diversification protects against economic shocks', 'Don''t put all your eggs in one basket—or one income stream. Civitas Dei helps you develop multiple revenue sources within the community.', '{"title": "Kingdom Portfolio: Multiple Streams of Provision", "intro": "The secular world teaches specialization: one job, one income. The Kingdom teaches diversification: multiple skills, multiple income streams, multiple sources of provision.", "verses": ["Invest in seven ventures, yes, in eight; you do not know what disaster may come upon the land. - Ecclesiastes 11:2", "The wise store up choice food and olive oil, but fools gulp theirs down. - Proverbs 21:20"], "examples": "A Civitas Dei member who teaches, codes, and does handyman work has three income streams. When one dries up, two remain. This is biblical risk management.", "actions": ["Identify 3 skills you can monetize", "Develop one new marketable skill per year", "Never depend on a single client for more than 40% of income", "Build passive income streams within the community"]}'),

('Mentorship multiplies your impact exponentially', 'You can do the work yourself, or you can teach 10 others to do it. Civitas Dei rewards mentors who multiply Kingdom capacity.', '{"title": "The Multiplication Economy: Training Up the Next Generation", "intro": "The secular economy hoards knowledge as competitive advantage. The Kingdom economy shares knowledge as multiplication strategy. When you train others, you build the Kingdom.", "verses": ["The things you have heard me say in the presence of many witnesses entrust to reliable people who will also be qualified to teach others. - 2 Timothy 2:2", "Iron sharpens iron, so one person sharpens another. - Proverbs 27:17"], "examples": "A Civitas Dei carpenter who trains 5 apprentices multiplies his Kingdom impact 5x. Those 5 train 25 more. This is exponential Kingdom growth.", "actions": ["Identify one person to mentor in your primary skill", "Teach openly, not secretively", "Celebrate when your mentee surpasses you", "Build a culture of learning, not gatekeeping"]}'),

('Local economy is more resilient than global economy', 'Global supply chains are fragile. Local communities are resilient. Civitas Dei builds economic strength at the local church level.', '{"title": "The Localization Principle: Building Resilient Communities", "intro": "Globalization promised efficiency but delivered fragility. When global supply chains break, local communities survive. Civitas Dei builds economic resilience at the most local level: your church.", "verses": ["Love your neighbor as yourself. - Mark 12:31", "Do good to all people, especially to those who belong to the family of believers. - Galatians 6:10"], "examples": "During COVID lockdowns, Civitas Dei communities continued functioning because they didn''t depend on global systems. Local services, local provision, local resilience.", "actions": ["Map all the skills available in your local church", "Commit to hiring from your community first", "Buy local before buying online", "Build relationships with local providers"]}'),

('The Kingdom economy is counter-cyclical to the world', 'When the world''s economy crashes, the Kingdom economy thrives. Civitas Dei is designed to be resilient when secular systems fail.', '{"title": "Counter-Cyclical Kingdom Economics", "intro": "The world''s economy runs on debt, speculation, and greed—all of which eventually collapse. The Kingdom economy runs on trust, generosity, and mutual aid—which grow stronger under pressure.", "verses": ["Do not store up for yourselves treasures on earth, where moths and vermin destroy, and where thieves break in and steal. But store up for yourselves treasures in heaven. - Matthew 6:19-20", "Though the fig tree does not bud and there are no grapes on the vines, yet I will rejoice in the Lord. - Habakkuk 3:17-18"], "examples": "In every major economic crisis—Great Depression, 2008 crash, COVID—communities with strong mutual aid networks survived better than individualists. Civitas Dei is that network, pre-built.", "actions": ["Reduce dependence on secular economic systems", "Build community wealth, not just personal wealth", "Prepare for disruption by strengthening local ties", "See economic crisis as opportunity for Kingdom growth"]}');

SELECT 'Keys table created and populated with 20 keys!' AS status;

